### ISSUE TITLE
Unsupported zip version

### ISSUE THREAD

**Issue by 1Map** [mhr3/unzip-stream#42]
I get error like:

```
Zip version 78.8 is not supported
at Immediate.<anonymous> (/myapp/node_modules/unzip-stream/lib/unzip-stream.js:355:33)
at processImmediate (node:internal/timers:464:21)
```

**Comment by mickeyjohn** [comment]
Hi @1Map ,
Could you please share a sample zip file for the error?
Thanks

**Comment by gazal-k** [comment]
Sample zip to reproduce the issue: [zip-78_8_not_supported.zip](https://github.com/mhr3/unzip-stream/files/10563694/zip-78_8_not_supported.zip)

Snippet for extraction:
```ts
createReadStream('/tmp/zip-78_8_not_supported.zip')
	.pipe(Parse())
	.on('entry', (entry: Entry) => {
		if (entry.type === 'Directory' || entry.path.startsWith('__MACOSX/') || entry.path.endsWith('.DS_Store')) {
			entry.autodrain();
			return;
		}
		console.log(`${entry.type} ${entry.path}`);
		entry.autodrain();
	}).on('close', () => console.log('done'));
```

Output:
```
File 63286267-IMG-000.jpg

<path>/node_modules/unzip-stream/lib/unzip-stream.js:355
            entry.emit("error", new Error(message));
                                ^
Error: Zip version 78.8 is not supported
    at Immediate.<anonymous> (<path>/node_modules/unzip-stream/lib/unzip-stream.js:355:33)
    at processImmediate (internal/timers.js:464:21)
```

**Comment by 1Map** [comment]
This is now more than a year, and still getting this error

**Comment by gazal-k** [comment]
This repository, like many other OSS projects may not have any sponsorship / funding. Someone would need to contribute to this out of their own goodwill or their paid work would need to allow for a contribution to this.
